language: go

go:
  - 1.5
env:
  - GO15VENDOREXPERIMENT=1
install:
  - go get github.com/Masterminds/glide
  - glide install
  - go get ./vendor/...
script:
  - go test -v -covermode=count  -bench . -cpu 1,4
